### ISSUE TITLE
chrome; Token Action HUD module; background color not obeyed

### ISSUE THREAD

**Issue by jcolson** [sdenec/tidy_ui#1]
for some reason when the tidy-ui-theme module is enabled on chrome, the Token Action HUD modules's configured background color is ignored for the menubar ... and it becomes transparent.  this does not occur in firefox.

<img width="686" alt="image" src="https://user-images.githubusercontent.com/2362647/128592417-140a7f83-88a9-4438-beec-8658c028f289.png">

**Comment by jcolson** [comment]
in firefox:
<img width="346" alt="image" src="https://user-images.githubusercontent.com/2362647/128592572-b892aeee-64c5-4fd7-a8c8-4988299da7d2.png">

in chrome:
<img width="490" alt="image" src="https://user-images.githubusercontent.com/2362647/128592581-20afafe1-bf97-4fef-ae3b-7bd55aefa7b6.png">

**Comment by sdenec** [comment]
Should be fixed. Color was overwritten by some javascript by the module itself. it is now !important and should stick.
Also some border issues for the controls are fixed. i believe this occurred with the latest core version.

Thanks for the report.
